build:
  image: google/dart:$$DART_VERSION
  pull: true
  commands:
    - sh build.sh
  environment:
    - DARTANALYZER_FLAGS=--fatal-warnings
matrix:
  DART_VERSION:
    - latest
publish:
  coverage:
    token: $$COVERAGE_TOKEN
    when:
      matrix:
        DART_VERSION: latest
