name: dogma_data
version: 0.0.1
description: Data serialization for Dart.
environment:
  sdk: '>=1.12.0-dev.4.0 <2.0.0'
dependencies:
  analyzer: '^0.26.0'
  args: '^0.13.2'
  cli_util: '^0.0.1+2'
  dart_style: '^0.2.0'
dev_dependencies:
  coverage: '^0.7.1'
  test: '^0.12.3+9'
