name: dogma_convert
version: 0.1.0
description: Data serialization for Dart.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
environment:
  sdk: '>=1.12.0 <2.0.0'
dev_dependencies:
  test: ^0.12.13
